// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  $(function() {
    var Arrow_Point;
    $('#container').masonry({
      itemSelector: '.item'
    });
    Arrow_Point = function() {
      var s;
      s = $("#container").find(".item");
      return $.each(s, function(i, obj) {
        var html, posLeft;
        posLeft = $(obj).css("left");
        if (posLeft === "0px") {
          html = "<span class='rightCorner'></span>";
          return $(obj).prepend(html);
        } else {
          html = "<span class='leftCorner'></span>";
          return $(obj).prepend(html);
        }
      });
    };
    Arrow_Point();
    $(".flybox").fancybox({
      'transitionIn': 'elastic',
      'transitionOut': 'elastic',
      'titlePosition': 'inside'
    });
    $("a[rel=group]").fancybox({
      'titlePosition': 'over',
      'cyclic': true,
      'titleFormat': function(title, currentArray, currenttitle, currentIndex, currentOpts) {
        return "<span id='fancybox-title-over'> " + (currentIndex + 1) + "/" + currentArray.length + " (" + title.length + " ?&nbsp;" + title + ":)</span>";
      }
    });
    $("#showdiv").fancybox({
      'centerOnScroll': 400
    });
    $("#iframe").fancybox({
      'width': '75%',
      'height': '75%',
      'autoScale': false
    });
    $("#swf").fancybox({
      'autoScale': false
    });
    return $("#modal").fancybox({
      'modal': false,
      'overlayShow': true,
      'hideOnOverlayClick': false,
      'hideOnContentClick': false,
      'enableEscapeButton': false,
      'showCloseButton': false,
      'centerOnScroll': true,
      'autoScale': false,
      'width': 540,
      'height': 360
    });
  });

}).call(this);
